teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.2
      y: 0.2
    scale_linear_turbo:
      x: 0.3
      y: 0.3
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 2.0
    enable_button: 4
    enable_turbo_button: 6
